#include <iostream>
#include <memory>
#include <cstdint>
#include <string>
#include "./../build_chain.hpp"
#include "./../generator.hpp"
#include "./../jacobian.hpp"

enum class GeneratorType{
  N_M_N_E,
  N_M_N_E_NNZ,
  UNKOWN
};

enum class JacobianType{
  JACOBIAN,
  DENSE_JACOBIAN,
  SPARSE_JACOBIAN,
  UNKOWN
};

GeneratorType parse_generator(const std::string& name){
  if (name == "n_m_n_E") return GeneratorType::N_M_N_E;
  if (name == "n_m_n_E_nnz") return GeneratorType::N_M_N_E_NNZ;
  return GeneratorType::UNKOWN;
}

JacobianType parse_jacobian(const std::string& name){
  if (name == "Jacobian") return JacobianType::JACOBIAN;
  else if (name == "Dense Jacobian") return JacobianType::DENSE_JACOBIAN;
  else if (name == "Sparse Jacobian") return JacobianType::SPARSE_JACOBIAN;
  return JacobianType::UNKOWN;
}

int main(){
  const std::vector<std::vector<std::size_t>> problem_data;

  std::string input_gen;
  std::cout << "Enter generator type {n_m_n_E , n_m_n_E_nnz} \n";
  std::cin >> input_gen;

  GeneratorType gen_type = parse_generator(input_gen);

  switch (gen_type){
    case GeneratorType::N_M_N_E{
      std::size_t chain_len, dim_lb, dim_ub, n_E_lb, n_E_ub, seed;
      bool is_deterministic;
      std::cout<< "Enter the arguments for the constructor.\n";
      std::cout<< "chain_len dim_lb dim_ub n_E_lb n_E_ub is_deterministic{0,1} seed\n";
      std::cin >> chain_len >> dim_lb >> dim_ub >> n_E_lb;
      std::cin >> n_E_ub >> is_deterministic >> seed;

      std::cout<< "Calling n_m_n_E_Generator constructor.\n";
      n_m_n_E_Generator gen{chain_len, dim_lb, dim_ub, n_E_lb, n_E_ub, is_deterministic, seed};
      std::cout<< "Building the problem.\n"
      gen.build_problem();
      std::cout<< "Copying problem data. \n";
      problem_data = gen.get_problem_copy(); 
      break;
    }

    case GeneratorType::N_M_N_E_NNZ: {
      std::size_t chain_len, dim_lb, dim_ub, n_E_lb, n_E_ub, seed;
      double den_lb, den_ub;
      bool is_deterministic;
      std::cout<< "Enter the arguments for the constructor.\n";
      std::cout<< "chain_len dim_lb dim_ub n_E_lb n_E_ub den_lb den_ub";
      std::cout<< " is_deterministic{0,1} seed\n";
      std::cin >> chain_len >> dim_lb >> dim_ub >> n_E_lb;
      std::cin >> n_E_ub >> den_lb >> den_ub >>is_deterministic >> seed;

      std::cout<< "Calling n_m_n_E_nnz_Generator constructor.\n";
      n_m_n_E_nnz_Generator gen{chain_len, dim_lb, dim_ub, n_E_lb, n_E_ub, 
          den_lb, den_ub, is_deterministic, seed};
      std::cout<< "Building the problem.\n";
      gen.build_problem();
      std::cout<< "Copying problem data. \n";
      problem_data = gen.get_problem_copy(); 
      break;
    }

    case GeneratorType::UNKOWN{
      std::cout << "Invalid input.\n"; 
    }
  }

  std::string input_jac;
  std::string sparse_data_file_name;
  std::cout << "Enter Jacobian type {Jacobian, Dense Jacobian, Sparse Jacobian} \n";
  std::cin >> input_jac;
  JacobianType jac_type = parse_generator(input_jac);

  switch (jac_type){
    case JacobianType::JACOBIAN{
      build_chain_implementation<Jacobian> build_chain_obj{problem_data}; 
    }
    case JacobianType::DENSE_JACOBIAN{
      build_chain_implementation<Jacobian> build_chain_obj{problem_data}; 
    }
    case JacobianType::SPARSE_JACOBIAN{
      if(gen_type != N_M_N_E_NNZ){
        std::cout << "Invalid generator. To create a sparse Jacobian chain the generator " <<
          "n_m_n_E_nnz_Generator must be called. \n";
      }
      std::cout << "Please enter the name of the file with the sparse structure.\n";
      std::cout << "If the sparse structure data to be used is the one generated by the generator " <<
        "sparse_data.\n";
      std::cin >> sparse_data_file_name;
      build_chain_implementation<Jacobian> build_chain_obj{problem_data, sparse_data_file_name}; 
    }
    case JacobianType::UNKOWN{
      std::cout << "Invalid input.\n"; 
    }
  }
  return 0;
}

